/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.Arrays;
public class App {

    public static void main(String[] args) {
        try{

        System.out.println("Welcome to PizzaHub");
        OrderService orderService = new OrderService();
        orderService.selectPizza("Whole wheat");
        orderService.selectSauce("Pesto sauce");
        orderService.addTopping(new ArrayList<>(Arrays.asList("Mozzarella Cheese","Pepperoni")));
        orderService.addDrink("Coke");
        orderService.addDesert("Lava Cake");
        orderService.checkout();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
}
