/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.Arrays;

public class App {

    public static void main(String[] args) {
        OrderService orderService = new OrderService();
        orderService.selectPizza("Regular");
        orderService.selectSauce("Marinara sauce");
        orderService.addToppings(new ArrayList<String>(Arrays.asList("Mozzarella Cheese","Spinach")));
        orderService.checkout();
    }
}
